config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'book#index'
 
 
    get 'libros/todos', to: 'book#index'
    get'libros/nuevo',to:'book#new'
    post'libros/crear',to: 'book#create'
    get 'libro/mostrar/:id', to: 'book#show'
    post 'libro/borrar/:id',  to: 'book#delete'

    get 'mis-libros/todos', to: 'userbook#index'
    post 'mis-libros/agregar', to: 'userbook#add'


  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :books, dependent: :destroy
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :author
    has_many :user_books
    has_many :users, through: :user_books
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_books
  has_many :books, through: :user_books
end

app/models/user_book.rb
class UserBook < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/book_controller.rb
class BookController < ApplicationController
before_action :authenticate_user!, only: [:new, :create, :delete]
    def index
    #hacemos una consulta de todos los libros a la base de datos
@books = Book.all
end
def new
    @authors = Author.all
end


def create
    book_params = params.require(:book).permit(:title, :description, :author_id)
    Book.create(book_params)
    redirect_to action: 'index'

end
def show
    @book = Book.find(params[:id])
     if @book.nil?
        redirect_to action: 'index'

     end
end

def delete
    @book = Book.find(params[:id])
    unless @book.nil?
        @book.delete

    end
    redirect_to action: 'index'

end

end

app/controllers/userbook_controller.rb
class UserbookController < ApplicationController
    before_action :authenticate_user!

    def index
        @books = current_user.books
    end

    def add
        book_id= params.require(:book).permit(:id)
        book= Book.find(book_id[:id])
       unless book.nil?
            current_user.books.push(book)
       end

       redirect_to action: 'index'

    end   

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/userbook_helper.rb
module UserbookHelper
end

app/views/book/index.html.erb
<ul>
        <% for book in @books%>

        <li>
        <a href="/libro/mostrar/<%= book.id %>">
        <%= book.title %></li>
        
        <% end %>
</ul>

app/views/book/new.html.erb
<h3>crear libro</h3>
<form method="post" action="<%=libros_crear_path%>">
<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
<div>
<label>Nombre</label>
<br>
<input type="text" placeholder="ingrese el nombre" name="book[title]">
</div>

<div>
<label>descripcion</label>
<br>
<textarea name="book[descripcion]"></textarea>
</div>


<div>
<label>Autor</label>
<br>
<select name="book[author_id]">
<% for author in @authors%>
<option value="<%= author.id %>">
<%= author.name%>
</option>
<% end %>
</select>
</div>

<div>
<button type="submit">Crear</button>
</div>
</form>

app/views/book/show.html.erb
<h2><%=@book.title%></h2>
<p><%= @book.description %> </p>
<form  method='post' action="/libro/borrar/<%= @book.id%>">
<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
<button type="submit">Borrar</button>
</form> 


    <% if user_signed_in? %>
    
    <form method="post" action="<%= mis_libros_agregar_path %>">
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        <input type="hidden" name="book[id]" value="<%= @book.id %>">
        <button type="submit">agregar Libro </button>
    </form>




<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookstore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
<% if user_signed_in? %>
<%= current_user.email %>
<a href="<%= destroy_user_session_path %>"
data-method="delete">
cerrar sesion 
</a>
<% else %>
<a  href="<%= new_user_session_path %>">
log in 
</a>
<a href="<%= new_user_registration_path %>">
registrarse
</a>

<% end %>
    <%= yield %>
  </body>
</html>

app/views/userbook/index.html.erb
<h1>
Libros Comprados
</h1>


<ul>
<% for book in @books%>
    <li><%= book.title %> </li>
<% end %>

</ul>